### ISSUE TITLE
v2ray 如何编译路由器版本呢

### ISSUE THREAD

**Issue by shanglanxin** [roylez/openwrt_pangolin#5]
路由器：wrt1900acs v2
使用的时候 v2ray 的 arm 固件太大，无法放入
精简编译的时候发现 v2ray 已经换了 bazel 的编译方式

或者有考虑使用外接u盘或者硬盘实现的方法嘛？

**Comment by cherrot** [comment]
> 精简编译的时候发现 v2ray 已经换了 bazel 的编译方式

我会尽快跟进，我还停留在3.48版本 :D 

不过`wrt1900acs` 在`/tmp/syscfg`有30MB的分区，应该够吧？

**Comment by shanglanxin** [comment]
我的安装之后分区只有20MB了，刚好不够，
不过我用 openwrt 扩展U盘的方式暂时绕过去了

**Comment by cherrot** [comment]
看了下，本质没变，只是换成了bazel编译链：

```shell
cd $GOPATH/src/v2ray.com/core
bazel build --action_env=GOPATH=$GOPATH --action_env=PATH=$PATH //release:v2ray_linux_arm_package
#Output: bazel-bin/release/v2ray-linux-arm.zip
```

供参考： https://www.v2ray.com/developer/intro/compile.html

**Comment by cherrot** [comment]
Just FYI:
```
11M Nov 21 22:07 v2ray_armv7
```
