### ISSUE TITLE
WR703N 固件

### ISSUE THREAD

**Issue by uo2022** [roylez/openwrt_pangolin#6]
我手上有一个WR703N，已经刷好的LEDE 固件。但不什么安装 shadowsocks，能否帮忙传一份你的备份给我呢。提前感谢。

**Comment by cherrot** [comment]
请阅读README.md

**Comment by cherrot** [comment]
FYI: 
<https://openwrt.org/toh/hwdata/tp-link/tp-link_tl-wr703n_v1>:
> Target: ar71xx
